version: '3.8'

services:
  admin-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "3632:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
    restart: always
    env_file:
      - api/.env
    depends_on:
      - admin-db

  nats:
    image: nats
    ports:
      - '1222:4222'